version: '3.8'

services:
  # Laravel Backend -PHP-FPM
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bank_backend
    restart: unless-stopped
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    networks:
      - bank_network
    environment:
      - PHP_MEMORY_LIMIT=512M  # limit do 512 MB
      - PHP_UPLOAD_MAX_FILESIZE=50M

  # Nginx Web Server -for Laravel
  nginx:
    image: nginx:alpine
    container_name: bank_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - bank_network
    depends_on:
      - backend

  # MySQL Database
  database:
    image: mysql:8.0
    container_name: bank_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bank_import
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bank_network

  # Vue 3 Frontend -Vite Dev Server
  frontend:
    image: node:20-alpine
    container_name: bank_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - bank_network

networks:
  bank_network:
    driver: bridge

volumes:
  db_data: